// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qR2VM4ZmfcFO6Fk5ZiJeJWRiDdAev6M',
    appId: '1:913552071291:web:018269507e7244c4ed20de',
    messagingSenderId: '913552071291',
    projectId: 'perfin-f656a',
    authDomain: 'perfin-f656a.firebaseapp.com',
    storageBucket: 'perfin-f656a.appspot.com',
    measurementId: 'G-N6M0GFYCB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaezDZI0beYZVrDqL8KhhFShLFNshIZKw',
    appId: '1:913552071291:android:9573081bf3f7da4ded20de',
    messagingSenderId: '913552071291',
    projectId: 'perfin-f656a',
    storageBucket: 'perfin-f656a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeV7njwENYkgylV6ZFi19ha0QnuIQlKCA',
    appId: '1:913552071291:ios:3bf8e479bb1234b2ed20de',
    messagingSenderId: '913552071291',
    projectId: 'perfin-f656a',
    storageBucket: 'perfin-f656a.appspot.com',
    iosBundleId: 'com.example.perfin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeV7njwENYkgylV6ZFi19ha0QnuIQlKCA',
    appId: '1:913552071291:ios:4f5e0fb929d4feb1ed20de',
    messagingSenderId: '913552071291',
    projectId: 'perfin-f656a',
    storageBucket: 'perfin-f656a.appspot.com',
    iosBundleId: 'com.example.perfin.RunnerTests',
  );
}
